baseURL = "https://pinpoint-workshop.com"
languageCode = "en-us"
title = "Amazon Pinpoint Workshop"
theme = "learn"

[params]
  AuthorName = "Daniel Geske, Neil Lock"
  GitHubUser = "aws-samples"
  SidebarRecentLimit = 5
  Subtitle = "Multichannel customer engagement using Amazon Pinpoint"
  themeVariant = "mine"



[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Amazon Pinpoint Documentation"
identifier = "documentation"
url = "https://docs.aws.amazon.com/pinpoint/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-twitter fa-lg'></i> @awscloud"
identifier = "twitter"
url = "https://twitter.com/intent/user?screen_name=awscloud"
weight = 20

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "github"
url = "https://github.com/aws-samples/amazon-pinpoint-workshop"
weight = 30