baseURL = "https://www.pinpoint-workshop.com"
languageCode = "en-us"
title = "Amazon Pinpoint Workshop"
theme = "learn"

[params]
  AuthorName = "Daniel Geske, Neil Lock"
  GitHubUser = "aws-samples"
  SidebarRecentLimit = 5
  Subtitle = "Multichannel customer engagement using Amazon Pinpoint"
  themeVariant = "mine"

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-home'></i> Amazon Pinpoint"
identifier = "homepage"
url = "https://aws.amazon.com/pinpoint/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-book'></i> Amazon Pinpoint Documentation"
identifier = "documentation"
url = "https://docs.aws.amazon.com/pinpoint/"
weight = 20

[[menu.shortcuts]]
name = "&nbsp; <i class='fas fa-fw fa-bookmark'></i> User Guide"
identifier = "userguide"
url = "https://docs.aws.amazon.com/pinpoint/latest/userguide/welcome.html"
weight = 30

[[menu.shortcuts]]
name = "&nbsp; <i class='fas fa-fw fa-bookmark'></i> Developer Guide"
identifier = "developerguide"
url = "https://docs.aws.amazon.com/pinpoint/latest/developerguide/welcome.html"
weight = 40

[[menu.shortcuts]]
name = "&nbsp; <i class='fas fa-fw fa-bookmark'></i> REST API Reference"
identifier = "apireference"
url = "https://docs.aws.amazon.com/pinpoint/latest/apireference/welcome.html"
weight = 50

[[menu.shortcuts]]
name = "&nbsp; <i class='fas fa-fw fa-bookmark'></i> SMS and Voice API Reference"
identifier = "pinpoint-sms-voice-apireference"
url = "https://docs.aws.amazon.com/pinpoint-sms-voice/latest/APIReference/welcome.html"
weight = 60

[[menu.shortcuts]]
name = "<i class='fab fa-twitter fa-lg'></i> @awscloud"
identifier = "twitter"
url = "https://twitter.com/intent/user?screen_name=awscloud"
weight = 80

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Workshop source"
identifier = "github"
url = "https://github.com/aws-samples/amazon-pinpoint-workshop"
weight = 90
